[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"
